name: Build Echo AI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate js/echo.js with OpenAI key
      - name: Inject OpenAI Key
        run: |
          mkdir -p js
          echo "const OPENAI_API_KEY = '${{ secrets.OPENAI_API_KEY }}';" > js/echo.js
          echo "console.log('Echo.js generated');" >> js/echo.js

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
          commit_message: "Auto deploy Echo AI"
