name: Build Echo AI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate js/echo.js with secret
      - name: Inject OpenAI Key
        run: |
          mkdir -p js
          echo "const OPENAI_API_KEY = '${{ secrets.OPENAI_API_KEY }}';" > js/echo.js
          echo "console.log('Echo.js generated')" >> js/echo.js

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
